### ISSUE TITLE
No months showing up for wtr.heatmap.layers

### ISSUE THREAD

**Issue by rjones933** [GLEON/rLakeAnalyzer#94] opened 2018-02-26 21:37 UTC
Having some issues with getting the months to show on the x-axis for the wtr.heatmap.layers function. They show up on the wrt.heat.map plot... has anyone had this issue before? We tried using the filled.contour function that is recommended to change defaults in the user manual but without success. 
![image](https://user-images.githubusercontent.com/36865483/36696824-4d0a8308-1b13-11e8-8400-d035cbb69f12.png) 
![image](https://user-images.githubusercontent.com/36865483/36696843-5eccfaee-1b13-11e8-9b1d-62973dcba35b.png)

**Comment by lawinslow** [comment] 2018-02-26 23:28
@rjones933 Good question. Not sure what's up with that, but I went in and fixed an issue I found in `wtr.heatmap.layers`. Want to give it a try and see if it fixes your issue? Install my github version using the command below:

```R
devtools::install_github('lawinslow/rLakeAnalyzer')
```
I think that should fix the issue you're seeing on the rLA version. Let me know if it does and I'll merge it in with the GLEON version.

**Comment by lawinslow** [comment] 2018-03-01 15:02
@rjones933 Did this fix your issue? If yes, I'd like to merge this into the main rLA branch and possibly push a new version to CRAN.

**Comment by lawinslow** [comment] 2018-03-05 13:47
@rjones933 Did this fix your issue? If yes, I'd like to merge this into the main rLA branch and possibly push a new version to CRAN.

**Comment by lawinslow** [comment] 2018-03-08 14:06
I'm going to close this and assume the issue is fixed.

**Closed by lawinslow** 2018-03-08 14:06 UTC
