### ISSUE TITLE
get.datetime error

### ISSUE THREAD

**Issue by shburnet** [GLEON/rLakeAnalyzer#97] opened 2018-08-08 19:46 UTC
I'm currently working on a headmap from my thermistor string data and am receiving errors for the following code:

> depths = get.offsets(wtr.all[,2:nn])
Warning message:
In drop.datetime(data) :
  Unable to find a datetime column. Assuming no datetime column was supplied.

Further code shows: 
> wtr.dates = get.datetime(wtr.all, error=TRUE)
Error in get.datetime(wtr.all, error = TRUE) : 
  could not find function "get.datetime"

My code prior to that works without error so I'm not sure what may be the issue since I can see datetime data is loaded.

Thanks in advance.

**Comment by shburnet** [comment] 2018-08-09 02:15
> head(wtr.all)
             datetime  wc_1  wc_3  wc_5  wc_6  wc_7  wc_8  wc_9 wc_10 wc_11 wc_13
1 2017-05-31 00:00:00 12.40 12.59 12.30 12.69 12.59 12.30 12.11 12.30 12.11 12.50
2 2017-05-31 01:00:00 11.24 11.43 11.14 11.53 11.24 11.04 10.65 10.85 10.65 11.33
3 2017-05-31 02:00:00 10.06 10.36 10.06 10.36 10.16  9.87  9.57  9.77  9.47 10.16
4 2017-05-31 03:00:00  9.47  9.77  9.47  9.77  9.57  9.37  8.88  9.18  8.88  9.57
5 2017-05-31 04:00:00  9.47  9.57  9.47  9.57  9.37  9.37  9.47  9.37  9.47  9.47
6 2017-05-31 05:00:00 11.33 11.33 11.24 11.53 11.53 11.53 11.53 11.53 11.43 11.53
  wc_16 wc_19 thermo.depth      top   bottom
1 12.40 12.88          NaN      NaN      NaN
2 11.14 11.63          NaN      NaN      NaN
3  9.97 10.55     7.959233 7.959233 7.959233
4  9.47  9.87          NaN      NaN      NaN
5  9.37  9.67          NaN      NaN      NaN
6 11.43 11.72          NaN      NaN      NaN

**Comment by jread-usgs** [comment] 2018-08-09 11:56
Can you post the function call you are using to make the heatmap?

are you using
```r
wtr.plot.temp(wtr.all[,1:nn])
```
?

Note from the examples you'll not want to exclude the `datetime` column, which is what I think you are doing when you use the "2" in `wtr.all[, 2:nn]`

**Comment by shburnet** [comment] 2018-08-15 16:41
I'm not using wtr.plot.temp as you mentioned above but I'll work on that next. 

Instead I was using the code from wtr.heatmap.layers.R page which I was able to get a temperature plot from.

**Comment by jread-usgs** [comment] 2018-08-15 16:50
Ok - are you no longer having an issue then?

**Comment by shburnet** [comment] 2018-08-16 22:31
Sorry, still having the issue when running the heatmap code. 

with wtr.all as you requested earlier I have:
> head(wtr.all)
             datetime  ms_1  ms_3  ms_5  ms_6  ms_7  ms_8  ms_9 ms_10 ms_11 ms_13
1 2017-05-31 00:00:00 12.30 12.88 12.69 13.08 12.40 12.79 12.59 12.50 12.21 12.30
2 2017-05-31 01:00:00 11.14 11.72 11.43 11.72 11.14 11.63 11.33 11.24 10.94 11.14
3 2017-05-31 02:00:00 10.06 10.55 10.36 10.75 10.16 10.55 10.26 10.06  9.87 10.06
4 2017-05-31 03:00:00  9.57  9.97  9.77 10.06  9.57  9.97  9.77  9.57  9.37  9.47
5 2017-05-31 04:00:00  9.37  9.57  9.47  9.67  9.47  9.57  9.47  9.47  9.37  9.28
6 2017-05-31 05:00:00 11.53 11.63 11.72 11.72 11.63 11.72 11.72 11.72 11.63 11.53
  ms_16 ms_19 ms_23 thermo.depth top bottom
1 12.11 12.88 12.30          NaN NaN    NaN
2 10.85 11.72 11.14          NaN NaN    NaN
3  9.87 10.65  9.97          NaN NaN    NaN
4  9.28 10.06  9.37          NaN NaN    NaN
5  9.28  9.57  9.47          NaN NaN    NaN
6 11.53 11.82 11.72          NaN NaN    NaN

When I reach:
 wtr.dates = get.datetime(wtr, error=TRUE)  # turn datetime into vector 

I have an error as I mentioned earlier: 
Error in get.datetime(wtr, error = TRUE) : 
  could not find function "get.datetime"

And with:
wtr.plot.temp(wtr.all[,1:nn])
Error in ts.thermo.depth(wtr, ...) : '...' used in an incorrect context
![image](https://user-images.githubusercontent.com/34756755/44238411-7b798680-a169-11e8-9a42-c311973b3393.png)

**Comment by jread-usgs** [comment] 2018-08-17 14:15
@shburnet please paste in the function call you are using, e.g., 

```r
library(rLakeAnalyzer)
wtr <- load.ts('my_temperatures.csv')
wtr.heatmap.layers(wtr)
```

I don't know what this code is that you are using, so it is hard to help:
> Instead I was using the code from wtr.heatmap.layers.R


You can get help on the `get.datetime()` function with
```r
?rLakeAnalyzer::get.datetime
```

**Comment by jread-usgs** [comment] 2019-09-16 15:59
@shburnet closing this issue because we don't have the details to reproduce it. If you can add them, please do so and re-open the issue.

**Closed by jread-usgs** 2019-09-16 15:59 UTC
